gui:
  theme:
    activeBorderColor:
      - '#f5e0dc'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    selectedLineBgColor:
      - '#313244'
    optionsTextColor:
      - '#89b4fa'